spring:
     application:
           name: MicroService-server
server:
   port: 8752
   
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    